-- Axe uses Auth.js JWT sessions for the website, so Auth.js adapter tables are not required.
-- Google-linked users, paid entitlements, one-time extension connections, and hashed
-- extension sessions are defined in db/schema.ts and managed through Drizzle.
